### ISSUE TITLE
columns.split is not a function

### ISSUE THREAD

**Issue by carlolucadei** [chriskinsman/DynamoDbExportCsv#11]
If you try to run it with the latest version of aws-sdk you got this kind of error

```
TypeError: columns.split is not a function
    at getItemWithHeaders (/Users/***/.config/yarn/global/node_modules/dynamodbexportcsv/lib/DynamoDbExportCsv.js:69:24)
```

I changed manually the code, removing split call since columns is already an array.

**Comment by taylor-knapp** [comment]
Unfortunately, I think the code on NPM is not the latest revision, because cloning the library and running without modifications works as expected.

**Comment by stephanebruckert** [comment]
@chriskinsman any chance you could update the version available on NPM? thx

**Comment by chriskinsman** [comment]
All updated.  Sorry about the delay.  0.2.7 is up there.
