### ISSUE TITLE
pull in aws creds from default directory

### ISSUE THREAD

**Issue by jamesw201** [chriskinsman/DynamoDbExportCsv#2]
hi, nice library. 

It would be nice if it searched for your aws creds in the usual places Ie. '~/.aws' so that you don't have to enter them as arguments to a search each time.

cheers

**Comment by chriskinsman** [comment]
That would be cool.  Might look at adding...

Open to a pull request

**Comment by chriskinsman** [comment]
Checked in #3 that includes this.

Thanks for the idea!
