### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by peralmq** [chriskinsman/DynamoDbExportCsv#6]
Hi,
thanks for a great package. The parallel scanning of the table is a great win for me and had some problems implementing that on my own.

I found a typo in your README. The package should be called `dynamodbexportcsv` and not `DynamoDBExportCSV` otherwise there will be problems installing it via `npm` (or `yarn`).

So change
```
  $ npm install DynamoDBExportCSV --save
```
to 
```
  $ npm install dynamodbexportcsv --save
```

**Comment by vitaly-zdanevich** [comment]
This issue still at https://www.npmjs.com/package/dynamodbexportcsv
