### ISSUE TITLE
support `--profile` argument or AWS_PROFILE env var

### ISSUE THREAD

**Issue by AlJohri** [chriskinsman/DynamoDbExportCsv#7]

**Comment by chriskinsman** [comment]
The code just uses the AWS Javascript SDK.  Does the SDK support the AWS_PROFILE env variable?  If so this should just work.

**Comment by chriskinsman** [comment]
Just validated the AWS Javascript SDK does pay attention to this environment variable.

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html

Please use this.
